// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/v1/point/point.proto

package point

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointServer_GetUserPoints_FullMethodName = "/point.PointServer/GetUserPoints"
)

// PointServerClient is the client API for PointServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointServerClient interface {
	GetUserPoints(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointReply, error)
}

type pointServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPointServerClient(cc grpc.ClientConnInterface) PointServerClient {
	return &pointServerClient{cc}
}

func (c *pointServerClient) GetUserPoints(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointReply)
	err := c.cc.Invoke(ctx, PointServer_GetUserPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointServerServer is the server API for PointServer service.
// All implementations must embed UnimplementedPointServerServer
// for forward compatibility.
type PointServerServer interface {
	GetUserPoints(context.Context, *PointRequest) (*PointReply, error)
	mustEmbedUnimplementedPointServerServer()
}

// UnimplementedPointServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointServerServer struct{}

func (UnimplementedPointServerServer) GetUserPoints(context.Context, *PointRequest) (*PointReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPoints not implemented")
}
func (UnimplementedPointServerServer) mustEmbedUnimplementedPointServerServer() {}
func (UnimplementedPointServerServer) testEmbeddedByValue()                     {}

// UnsafePointServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointServerServer will
// result in compilation errors.
type UnsafePointServerServer interface {
	mustEmbedUnimplementedPointServerServer()
}

func RegisterPointServerServer(s grpc.ServiceRegistrar, srv PointServerServer) {
	// If the following call pancis, it indicates UnimplementedPointServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointServer_ServiceDesc, srv)
}

func _PointServer_GetUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServerServer).GetUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointServer_GetUserPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServerServer).GetUserPoints(ctx, req.(*PointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointServer_ServiceDesc is the grpc.ServiceDesc for PointServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "point.PointServer",
	HandlerType: (*PointServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPoints",
			Handler:    _PointServer_GetUserPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/point/point.proto",
}
